#!/bin/bash
#title 						:cheat.sh
#description			:Small UI for cheat.sh website
#author						:Owen Cocjin
#co-author				:No one right now
#notes						:Internet connection required

## ---------- FUNCTIONS ---------- ##
function usage(){
	echo -e '''
\n\e[33mUsage:\e[0m cheat [-qclh] [VALUES]
\tA quick way to utilize the cheat.sh website. Note that the order the flags appear in
\n\e[33mArguments:\e[0m
\t-h, --help\tPrints this screen
\t-l,       \tSets the language. Requires -q flag
\t-q,       \tTo ask a question. Must be in the format: -q [LANGUAGE] \"[QUESTION]\". Requires -l flag
\t-c,       \tSets command. Must be the only flag set when using
\n
'''
	exit 0
}

function getCheat(){
	echo "Getting answer..."
	printf -v s '%*s' "$COLUMNS"
	echo -ne "\n\e[34m${s// /*}\e[39m"
	echo -ne "\e[34m${s// /*}\e[39m\n\n\n"
	curl cheat.sh/$lanOrCom/${question// /+}
	echo -ne "\n\n\e[34m${s// /*}\e[39m"
	echo -ne "\e[34m${s// /*}\e[39m\n\n"
	exit 0
}

## ---------- VARIABLES ---------- ##
question=""
lanOrCom=""
com=""

## ---------- MAIN ---------- ##
# Check if cheat.sh is reachable
ping -c 1 cheat.sh &>/dev/null
if [[ "$?" != "0" ]]; then
	echo "Unable to reach cheat.sh site :("
	exit 1
fi

#If no flags were set, print usage
if [[ "$#" == "0" ]] || [[ "${1:0:1}" != "-" ]]; then
	usage
fi

while getopts :hl:c:q:-: opt; do
  case $opt in
		q)
			question="$OPTARG"
			con=""
		;;
		l)
			lanOrCom="$OPTARG"
			con=""
		;;
		c)
			if [[ "$#" == 2 ]]; then
				con="$OPTARG"
				lanOrCom="$con"
				question=""
				getCheat
			else
				echo "Cannot use multiple flags in conjunction with -c"
				echo -e "See \e[1mcheat --help\e[0m for usage"
				exit 0
			fi
		;;
		h|-|*)
			if [[ "$OPTARG" -eq "help" ]] || [[ -z "$OPTARG" ]]; then
				usage
			fi
		;;
	esac
done

#Check if question flag is raised with language
#This checks is question is blank,
if [[ -n "$question" ]] && [[ -n "$lanOrCom" ]]; then
	getCheat
else
	usage
fi
